### ISSUE TITLE
Add linting configuration and fix lint errors

### ISSUE THREAD

**Issue by akariv** [hasadna/OpenCaptcha#3]
Use pylama or similar to maintain a consistent coding style.

**Comment by ronniemaor** [comment]
Could you add more details on how the linter is integrated with the testing environment (travis) on your projects and whether you just use default options or have a specific config? An example project to use as reference would be very helpful.

**Comment by akariv** [comment]
Pylama with default settings should work.

**Comment by akariv** [comment]
see here for example 
https://github.com/okfn/oki-py

**Comment by zivmaor** [comment]
Having trouble debugging this on travis due to no logs:
https://github.com/travis-ci/travis-ci/issues/7443#issuecomment-615875020

Will try to get it working locally and see if once it passes locally it just works on travis...

**Comment by akariv** [comment]
Seems to be working now

https://travis-ci.org/github/hasadna/OpenCaptcha/jobs/676587406

**Comment by zivmaor** [comment]
You can only see the logs while the test is running. Clicking your link now showed me empty logs :-(

However, we managed to fix all errors by looking at the logs while the process was running. There were only issues related to line length > 79.

**Comment by akariv** [comment]
I'm guessing this is a temporary issue.
Either way you should be able to run the tests / lint locally as well, no?

**Comment by zivmaor** [comment]
I agree it's probably a temporary issue.
No, I can't run the linter locally because I haven't figured out how to configure !@#$ tox in my environment. Been fighting with it for a while and can't get it to work. I don't know if it's because things don't work as smoothly on windows or I haven't found the magic incantation or something stupid I'm missing, but I don't have time to fight with it any more at the moment. Moving on.
